version: '3.1'
services:
  web:
    build: .
    image: gowebapp
    restart: always
    ports:
      - 8080:8080
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: api_vote
    volumes:
      - ./initdb.sql:/docker-entrypoint-initdb.d/initdb.sql